### PR TITLE
Write all files into log dir

### PR DESCRIPTION
**Pull request by normanrz**
Write all temporary and log files into a configurable directory instead of the current working directory. By default the folder `.cfut` is used, but configurable by `CFUT_DIR` env variable.

### CODE REVIEW

**Comment by normanrz** [comment]
This PR also includes support for Python3

**Comment by sampsyo** [comment]
Cool! This all looks great! Thanks! I didn't know there was a Python 3-compatible extraction of the picloud pickling library.

**Comment by normanrz** [comment]
Thanks for merging my PR! It would be amazing, if you could make a new version on PyPi :-)

**Comment by sampsyo** [comment]
Done! https://pypi.org/project/clusterfutures/0.3/

**Pull request merged**
