### PR TITLE
Miscellaneous cleanup

### PR DESCRIPTION
**Pull request by takluyver**
Me again :wink: . I noticed a few warnings in my IDE as I was working on the tests. These are simple cleanups which shouldn't change any functionality.

### CODE REVIEW

**Comment by sampsyo** [comment]
Nice; hard to argue with these. Thanks!! I'll make you a collaborator on this repo so you can push directly if you see fit, but please feel free to open PRs if you want a casual code review. :smiley:

**Comment by takluyver** [comment]
Thanks! I'll continue to open PRs - I'm used to working that way even on projects where I have push rights. But if you're too busy to look at them, just let me know. A couple of my colleagues at European XFEL are using clusterfutures, so I can also ask them to look at my changes.

Would you be happy to add me to the project on PyPI as well (user takowl), so I can upload a new release at some point? I'm thinking of some more minor changes first, but there's not a lot to do. :slightly_smiling_face:

**Comment by sampsyo** [comment]
Sounds great! And sure thing; I just invited you to the PyPI project.

**Comment by takluyver** [comment]
Thanks again :grinning:

**Pull request merged**
